project:
  name: rag_rfp_analyzer
  target_document: "고려대학교_차세대 포털·학사 정보시스템 구축사업"

path:
  metadata_file: "data/data_list.csv"
  file_dir: "data/raw_pdf"
  raw_pdf_file: "data/raw_pdf/고려대학교_차세대 포털·학사 정보시스템 구축사업.pdf"
  pdf_pages:
  image_dir: "outputs/images"
  write_images: false
